import type { Metadata } from "next";
import { Manrope, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/providers/user-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// import {
//   ClerkProvider
// } from '@clerk/nextjs';

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <UserProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <Toaster position="top-right" />
        </body>
      </html>
    </UserProvider>  
    // </ClerkProvider>
  );
}
